# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "github-main" ]
  pull_request:
    branches: [ "github-main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: containers.ligo.org/lscsoft/bilby/v2-bilby-python310
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Install package
      run: |
        python -m pip install .
        conda list --show-channel-urls
    - name: Run precommits
      run: |
        pre-commit run --all-files --verbose --show-diff-on-failure
    - name: Run unit tests
      run: |
        pytest --cov-bilby --durations 10
    - name: Run sampler tests
      run: |
        pytest test/integration/sampler_run_test.py --durations 10 -v
